#!/usr/bin/env bash
set -e

options=(
  style=round
  width=8.0
  hidpi=on
  ax_focus=on
  active_color=0xffc15f3c
  inactive_color=0xff494d64
  order=above
  blacklist="Wispr Flow,Setapp"
)

borders "${options[@]}"
